---
- name: all server deploy
  hosts: all
  roles:
    - initdb
  become: yes
  become_user: root
  become_method: sudo

- name: pub server setting
  hosts: pub_servers
  roles:
    - pub
  become: yes
  become_user: root
  become_method: sudo

- name: sub server setting
  hosts: sub_servers
  roles:
    - sub
  become: yes
  become_user: root
  become_method: sudo

