---
  - name: Copy postgresql.conf
    copy:
      src: postgresql.conf
      dest: "{{__postgresql_data_dir}}"/postgresql.conf
      owner: "{{ postgres_user }}"
      group: "{{ postgres_group }}"
      mode: 0600
      backup: yes

  - name: Copy pg_hba.conf
    copy:
      src: pg_hba.conf
      dest: "{{__postgresql_data_dir}}"/pg_hba.conf
      owner: "{{ postgres_user }}"
      group: "{{ postgres_group }}"
      mode: 0600

  - name: Create User


  - name : Copy make.pl
    copu:
      src: makedb.pl
      destL: makedb.pl
      mode: 0755

