---
  - name: Copy postgresql.conf
    copy:
      src: postgresql.conf
      dest: postgresql.conf
      owner: "{{ postgres_user }}"
      group: "{{ postgres_group }}"
      mode: 0600
      backup: yes

  - name: Copy pg_hba.conf
    copy:
      src: pg_hba.conf
      dest: pg_hba.conf
      owner: "{{ postgres_user }}"
      group: "{{ postgres_group }}"
      mode: 0600
      
  - name: 
  