---
- name: install apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb

- name: set root pass
  mysql_user:
    name: root
    host_all: yes
    password: "{{DB_ROOT_PASSWORD}}"
    login_user: root

- name: create database
  mysql_db:
    name: "{{DB_NAME}}"
    state: present

- name: create user
  mysql_user:
    name: "{{DB_USER}}"
    host: localhost
    password: "{{DB_PASS}}"
    priv: "{{DB_NAME}}.*:ALL"
    state: present