---
- name: Install PHP
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - php-pear
    - php7.0
    - php7.0-gmp
    - php7.0-mysql
    - php7.0-mbstring
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-curl
  
- name: enable php
  command: a2enmod php7.0
